name: "Collect Test Data"
description: "Collect test data and metadata and upload them to GCS."
inputs:
  path:
    description: "The path to the test output (such as a JUnit XML file)."
    required: true
  gcs_path:
    description: |
      The GCS bucket and optional prefix to upload the test data and metadata to.
      The format is bucket-name[/prefix]. You don't need to include the gs:// prefix.
    required: true
  gcp_project_id:
    description: "The GCP project ID to use for authentication."
    required: true
  workload_identity_provider:
    description: "The workload identity provider to use for authentication."
    required: true
  service_account_email:
    description: "The service account email to use for authentication."
    required: true
outputs:
  uploaded:
    description: "The list of files uploaded to GCS."
    value: ${{ steps.upload.outputs.uploaded }}
runs:
  using: "composite"
  steps:
    - name: set more GITHUB_ vars
      shell: bash -euo pipefail {0}
      env:
        GITHUB_MATRIX: ${{toJSON(matrix)}}
        GITHUB_MATRIX_INDEX: ${{toJSON(strategy.job-index)}}
        GITHUB_MATRIX_TOTAL: ${{toJSON(strategy.job-total)}}

        # required for the below API call
        GH_TOKEN: ${{ github.token }}
      run: ${{ github.action_path }}/bin/set-job-vars

    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: "3.11"

    - name: Prepare
      shell: bash -euo pipefail {0}
      run: |
        set -x
        mkdir -p test-data
        cp -r ${{ inputs.path }} test-data
        python3 -uS ${{ github.action_path }}/bin/generate-metadata > test-data/metadata.json

    - name: Authenticate
      uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c # v2.1.2
      with:
        project_id: ${{ inputs.gcp_project_id }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account_email }}

    - name: Upload
      id: upload
      uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # v2.1.0
      with:
        path: test-data
        destination: ${{ inputs.gcs_path }}
