name: Self-Test

on:
  push:
    branches:
      - main
  pull_request: null

defaults:
  run:
    shell: bash -euxo pipefail {0}
env:
  PS4: "\e[36m$\e[m "

jobs:
  reglar:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Action
        id: test-action
        uses: ./pytest
        with:
          _deploy_environ: dev
          _gcp_project: di-dev-mtr--buck-5

      - name: Check Output
        env:
          files: ${{ steps.test-action.outputs.uploaded }}
        run: |
          # Check that both files were uploaded (using the output from the action)
          if [[ $files != *'pytest-report.json'* ]]; then
            echo "pytest-report.json not uploaded"
            exit 1
          fi
          if [[ $files != *'metadata.json'* ]]; then
            echo "metadata.json not uploaded"
            exit 1
          fi
          echo "Files uploaded successfully"

  with-matrix:
    strategy:
      matrix:
        key: [2, 37]

    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Action
        id: test-action
        uses: ./pytest
        with:
          _deploy_environ: dev
          _gcp_project: di-dev-mtr--buck-5

      - name: Check Output
        env:
          files: ${{ steps.test-action.outputs.uploaded }}
        run: |
          # Check that both files were uploaded (using the output from the action)
          if [[ $files != *'pytest-report.json'* ]]; then
            echo "pytest-report.json not uploaded"
            exit 1
          fi
          if [[ $files != *'metadata.json'* ]]; then
            echo "metadata.json not uploaded"
            exit 1
          fi
          echo "Files uploaded successfully"
